// Generated by CoffeeScript 1.3.1

/* --------------------------------------------------------
	 flowGrid v 1.0
	 @author Pierre Laveklint
	 @company KAN MalmÃ¶
--------------------------------------------------------
*/


(function($, window, undefined) {
	var $, GridElement;

	$ = jQuery;

	$.fn.extend({
		flowGridRemove: function() {
			return $(this).trigger('flowGridRemove');
		},
		refresh: function() {
			return $(this).trigger('flowGridRefresh');
		},
		flowGrid: function(options) {
			this.flowGridRemove();
			var container, settings,
			_this = this;

			settings = {
				hspace: 8,
				vspace: 8,
				isAnimated: true,
				isResizeable: true,
				animOptions: {
					duration:400
				}
			};

			settings = $.extend(settings, options);

			container = $(this);

			return this.each(function() {

				var checkForSizeChange, childCount, children, columnWidth, firstChild, init, layout, wrapTimer, _handleGridElement, _updateSavedSize;
				children = [];
				children = _this.children();
				childCount = children.length;
				firstChild = children.eq(0);
				columnWidth = firstChild.outerWidth();

				init = function() {
					var that = this;
					this.isLayedOut = false;
					children.css({ position: 'absolute' }).addClass('flowgrid-brick');
					layout();

					container.preloadImages(function(){
						container.show();
						layout();
					}, false );
				};

				layout = function() {
					var availableWidth, child, childIndex, column, columnHeight, columns, consumedWidth, height, leftOver, marginBottom, marginRight, maxColumn, offsetX, shortestColumn, x, y, _i, _j, _ref;

					marginRight = settings.hspace;
					marginBottom = settings.vspace;
					availableWidth = $(container).width();

					columns = Math.max(Math.floor((availableWidth + marginRight) / (columnWidth + marginRight)), 1);
					consumedWidth = columns * columnWidth + (columns - 1) * marginRight;
					leftOver = Math.max(availableWidth - consumedWidth, 0);

					offsetX = 0;
					columnHeight = [];
					childIndex = -1;

					var styleFn = !this.isLayedOut ? 'css' : ( settings.isAnimated ? 'animate' : 'css'),
						animOptions = settings.animOptions;

					for (childIndex = _i = 0; 0 <= childCount ? _i <= childCount : _i >= childCount; childIndex = 0 <= childCount ? ++_i : --_i) {
						shortestColumn = 0;
						column = 0;
						for (column = _j = 0, _ref = columns - 1; 0 <= _ref ? _j <= _ref : _j >= _ref; column = 0 <= _ref ? ++_j : --_j) {
							height = columnHeight[column] || 0;
							if (height < columnHeight[shortestColumn]) {
							shortestColumn = column;
							}
						}
						x = shortestColumn * (columnWidth + marginRight) + offsetX;
						y = columnHeight[shortestColumn] || 0;
						child = children.eq(childIndex);
						
						child[styleFn]({
							left: x+'px',
							top: y+'px'
						},animOptions)

						columnHeight[shortestColumn] = y + child.outerHeight() + marginBottom;
						maxColumn = Math.max.apply(_this, columnHeight);
						$(container).css({
							'height': "" + maxColumn + "px"
						});
					}

					this.isLayedOut = true;
				};

				$(_this).bind('flowGridRemove', function() {
					if (settings.isResizeable === true) {
						$(window).unbind( 'smartresize.flowgrid', layout);
					}
					$(container).unbind();
					return $(_this).unbind();
				});

				$(_this).bind('flowGridRefresh', function() {
					return layout();
				});

				if (settings.isResizeable === true) {
					// $(window).bind('resize', layout);
					$(window).bind( 'smartresize.flowgrid', layout);
				}

				init();

				return _this;
			});
		}
	});

	/*
	* smartresize: debounced resize event for jQuery
	*
	* latest version and complete README available on Github:
	* https://github.com/louisremi/jquery.smartresize.js
	*
	* Copyright 2011 @louis_remi
	* Licensed under the MIT license.
	*/

	var $event = $.event,
	resizeTimeout;

	$event.special.smartresize = {
		setup: function() {
			$(this).bind( "resize", $event.special.smartresize.handler );
		},
		
		teardown: function() {
			$(this).unbind( "resize", $event.special.smartresize.handler );
		},
		
		handler: function( event, execAsap ) {
			// Save the context
			var context = this,
			  args = arguments;

			// set correct event type
			event.type = "smartresize";

			if ( resizeTimeout ) { clearTimeout( resizeTimeout ); }
			resizeTimeout = setTimeout(function() {
				$.event.handle.apply( context, args );
			}, execAsap === "execAsap"? 0 : 100 );
		}	
	};

	$.fn.smartresize = function( fn ) {
		return fn ? this.bind( "smartresize", fn ) : this.trigger( "smartresize", ["execAsap"] );
	};

	

	/* Get all images of container and preload
	*  Triggers callback after each image loaded or after all images loaded
	*/

	$.fn.preloadImages = function( callback, hurry ) {
		var $this = this,
			$images = $this.find('img').add( $this.filter('img') ),
			total = $images.length,
			blank = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==',
			loaded = [];

		function triggerCallback() {
			callback.call( $this, $images );
		}

		function imageLoaded(event) {
			var img = event.target;
			if( img.src !== blank && $.inArray( img, loaded ) === -1 ) {
				loaded.push(img);
				if( hurry === true ) setTimeout( triggerCallback );
				if( --total <= 0 ) {
					setTimeout( triggerCallback );
					$images.unbind( '.imagesLoaded', imageLoaded );
				}
			}
		}
		if( !total ) { triggerCallback(); }

		$images.bind( 'load.imagesLoaded error.imagesLoaded', imageLoaded ).each( function() {
			var that = this;
			setTimeout(function(){

			var src = that.src;
			that.src = blank;
			that.src = src;
			});
		});

		return $this;
	}

})(jQuery, window);